# -*- coding: utf-8 -*-
"""demo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WH05upRZGslIzYxTN-8fJYHts0_uzJhk
"""

!pip install streamlit

!pip install crewai
!pip install -qU tokenizers>=0.15,<0.16

!pip install langchain

!pip install --upgrade langchain
!pip uninstall langchain langchain-core langchain-text-splitters
!pip install langchain==0.1.10 langchain-core==0.1.52
!pip install crewai embedchain langchain-community

!pip uninstall langchain langchain-core crewai
!pip install langchain==0.1.10 langchain-core==0.1.52 crewai==0.30.11

import os
import streamlit as st
from crewai import Agent, Task, Crew
from langchain.llms import OpenAI

# Set your OpenAI API key (make sure to replace 'your_openai_api_key_here' with your actual key)
openai_api_key = os.getenv("OPENAI_API_KEY", "sk-proj-SR3mBMXzaw6dQG3WoGlzT3BlbkFJbPSV69wzuMEG679WnoHH")

# Define your agents
question_creator = Agent(
    name="Question Creator",
    llm=OpenAI(temperature=0.8, openai_api_key=openai_api_key),
    role="creator",  # Add the required role
    goal="Create challenging and thought-provoking questions for IIT-JEE aspirants.",  # Add the required goal
    backstory="An expert in creating complex and analytical questions to test students' problem-solving skills."  # Add the required backstory
)

question_reviewer = Agent(
    name="Question Reviewer",
    llm=OpenAI(temperature=0.8, openai_api_key=openai_api_key),
    role="reviewer",  # Add the required role
    goal="Review and assess the quality of IIT-JEE questions for clarity and relevance.",  # Add the required goal
    backstory="A seasoned educator with extensive experience in evaluating the quality and relevance of exam questions."  # Add the required backstory
)

# Define your crew
crew = Crew(
    agents=[question_creator, question_reviewer],
    tasks=[],  # Assuming task1 and task2 are not defined yet
    verbose=1,
)

# Define Streamlit app UI
st.title("IIT-JEE Question Creator and Reviewer")
task_options = ["Create IIT-JEE Question", "Review IIT-JEE Question"]

# Define functions to handle task execution
def execute_task(task_index):
    st.subheader(f"Task: {task_options[task_index]}")
    if task_index == 0:  # Create IIT-JEE Question
        question = st.text_area("Enter the question statement:")
        answer = st.text_input("Enter the correct answer:")
        explanation = st.text_area("Enter the detailed explanation:")
        if st.button("Submit Question"):
            # Perform task execution
            result = crew.agents[0].llm.generate(prompt=f"Create a challenging and thought-provoking question for IIT-JEE aspirants on the topic of {question}. The question should test the analytical skills, problem-solving abilities, and conceptual understanding of the students. The correct answer is {answer}. Provide a detailed explanation of the answer: {explanation}")
            st.write("Question Created Successfully!")
            st.write("Result:", result)
    elif task_index == 1:  # Review IIT-JEE Question
        question_to_review = st.text_area("Enter the question to review:")
        if st.button("Review Question"):
            # Perform task execution
            result = crew.agents[1].llm.generate(prompt=f"Review the IIT-JEE question: {question_to_review}. Assess its quality, relevance to the IIT-JEE syllabus, difficulty level, and clarity. Provide feedback and suggestions for improvement if necessary.")
            st.write("Question Reviewed Successfully!")
            st.write("Result:", result)

# Main Streamlit app logic
task_index = st.radio("Select Task:", options=task_options)
execute_task(task_options.index(task_index))

!streamlit run iitjee.py

!pip install streamlit
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

streamlit_code = """
import streamlit as st

st.title('Hello Streamlit!')
st.write("This is your first Streamlit app.")
"""

with open('iitjee.py', 'w') as f:
    f.write(streamlit_code)

!streamlit run iitjee.py &>/dev/null&

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

